"""Frozen V1 mobile workbench shell for the tutoring-center dashboard."""

from __future__ import annotations


DASHBOARD_WORKBENCH_V1_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="color-scheme" content="light">
  <title>小优工作台</title>
  <style>
    :root{
      color-scheme:light;--brand:#167a5a;--brand-dark:#0f5f46;--brand-soft:#eaf5f0;
      --info:#2f6fed;--info-soft:#edf3ff;--warning:#a75d12;--warning-soft:#fff4e5;
      --danger:#b93838;--danger-soft:#fff0f0;--ink:#18211d;--secondary:#53605a;
      --muted:#7a8580;--line:#dfe5e2;--strong:#cbd5d0;--surface:#fff;
      --canvas:#eef2f0;--subtle:#f6f8f7;--radius:8px;--nav-height:70px
    }
    *{box-sizing:border-box} html{background:var(--canvas)}
    body{margin:0;color:var(--ink);background:var(--canvas);font-family:"Microsoft YaHei","PingFang SC",system-ui,-apple-system,"Segoe UI",sans-serif;font-size:15px;letter-spacing:0}
    button,input,select{font:inherit;letter-spacing:0} button{-webkit-tap-highlight-color:transparent}
    .app{width:min(520px,100%);min-height:100dvh;margin:0 auto;background:var(--surface);box-shadow:0 10px 30px rgba(23,42,33,.08)}
    .top{position:sticky;top:0;z-index:10;padding:14px 16px 12px;border-bottom:1px solid var(--line);background:rgba(255,255,255,.97)}
    .brand-row{display:flex;align-items:center;gap:10px}.brand-mark{width:40px;height:40px;display:grid;place-items:center;flex:0 0 40px;border-radius:var(--radius);color:#fff;background:var(--brand);font-size:20px;font-weight:800}
    .brand-copy{min-width:0;flex:1}.brand-title{margin:0;font-size:20px;line-height:1.25}.brand-sub{margin-top:2px;color:var(--secondary);font-size:13px;line-height:1.4}
    .role-badge{padding:5px 8px;border-radius:999px;color:var(--brand-dark);background:var(--brand-soft);font-size:13px;font-weight:700}
    .context{margin-top:10px;display:flex;justify-content:space-between;gap:10px;color:var(--muted);font-size:12px}.context span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    main{padding-bottom:calc(var(--nav-height) + env(safe-area-inset-bottom) + 18px)}
    .intro{padding:20px 16px;background:var(--subtle);border-bottom:1px solid var(--line)}
    .eyebrow{color:var(--brand-dark);font-size:13px;font-weight:700}.intro h2{margin:7px 0 6px;font-size:24px;line-height:1.3}.intro p{margin:0;color:var(--secondary);line-height:1.65}
    .section{padding:20px 16px 5px;border-bottom:1px solid var(--line)}.section:last-child{border-bottom:0}
    .section-head{margin-bottom:12px;display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.section h3{margin:0;font-size:17px;line-height:1.4}.section-note{color:var(--muted);font-size:12px;text-align:right}
    .list{display:grid;gap:8px;margin:0 0 15px}.item{width:100%;min-height:66px;padding:12px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;text-align:left;color:inherit;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius)}
    button.item{cursor:pointer}.item:active{background:var(--subtle)}.item-copy{min-width:0}.item-title{font-weight:700;line-height:1.45;overflow-wrap:anywhere}.item-summary{margin-top:4px;color:var(--secondary);font-size:13px;line-height:1.55;overflow-wrap:anywhere}.item-meta{margin-top:6px;color:var(--muted);font-size:12px;line-height:1.45}.chevron{color:var(--muted);font-size:20px}.accent{border-left:3px solid var(--brand)}.info{border-left:3px solid var(--info)}.warning{border-left:3px solid var(--warning)}.danger{border-left:3px solid var(--danger)}
    .tag{display:inline-flex;align-items:center;min-height:24px;padding:2px 7px;border-radius:999px;color:var(--secondary);background:var(--subtle);font-size:12px;font-weight:700}.tag.green{color:var(--brand-dark);background:var(--brand-soft)}.tag.blue{color:var(--info);background:var(--info-soft)}.tag.amber{color:var(--warning);background:var(--warning-soft)}.tag.red{color:var(--danger);background:var(--danger-soft)}
    .metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-bottom:15px}.metric{min-height:88px;padding:12px;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface)}.metric-label{color:var(--secondary);font-size:13px}.metric-value{margin-top:8px;font-size:24px;font-weight:800;line-height:1}.metric-foot{margin-top:7px;color:var(--muted);font-size:12px}
    .empty{margin-bottom:15px;padding:18px 14px;text-align:center;border:1px dashed var(--strong);border-radius:var(--radius);background:var(--subtle)}.empty strong{display:block}.empty p{margin:6px 0 0;color:var(--muted);font-size:13px;line-height:1.55}
    .notice{margin-bottom:15px;padding:12px;border-left:3px solid var(--brand);background:var(--brand-soft);line-height:1.6}.notice strong{display:block;margin-bottom:2px}.notice.warning{background:var(--warning-soft)}
    .toolbar{display:flex;gap:8px;margin-bottom:12px}.search{width:100%;min-height:44px;padding:0 12px;border:1px solid var(--strong);border-radius:var(--radius);background:#fff;color:var(--ink)}
    .filters{display:flex;gap:7px;margin-bottom:12px}.filter{min-height:36px;padding:0 12px;border:1px solid var(--strong);border-radius:999px;background:#fff;color:var(--secondary)}.filter.active{border-color:var(--brand);color:#fff;background:var(--brand)}
    .program-select{min-height:40px;padding:0 30px 0 10px;border:1px solid var(--strong);border-radius:var(--radius);background:#fff;color:var(--ink)}
    .source-line{margin:-5px 0 14px;color:var(--muted);font-size:12px;line-height:1.5}.fact-label{color:var(--brand-dark);font-weight:700}.judgement-label{color:var(--info);font-weight:700}
    .nav{position:fixed;left:50%;bottom:0;z-index:20;width:min(520px,100%);min-height:calc(var(--nav-height) + env(safe-area-inset-bottom));padding:6px 8px env(safe-area-inset-bottom);display:grid;gap:4px;border-top:1px solid var(--line);background:rgba(255,255,255,.98);transform:translateX(-50%)}
    .nav button{min-width:0;min-height:56px;padding:4px 2px;border:0;background:transparent;color:var(--muted);font-size:12px}.nav button::before{content:"";display:block;width:18px;height:3px;margin:0 auto 7px;border-radius:2px;background:transparent}.nav button.active{color:var(--brand-dark);font-weight:800}.nav button.active::before{background:var(--brand)}
    .loading{padding:80px 24px;text-align:center;color:var(--muted)}.spinner{width:30px;height:30px;margin:0 auto 14px;border:3px solid var(--line);border-top-color:var(--brand);border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
    dialog{width:min(520px,100%);max-width:none;max-height:82dvh;margin:auto auto 0;padding:0;border:0;border-radius:8px 8px 0 0;background:#fff;color:var(--ink)}dialog::backdrop{background:rgba(15,28,22,.46)}
    .sheet-head{position:sticky;top:0;padding:16px 50px 13px 16px;border-bottom:1px solid var(--line);background:#fff}.sheet-head h3{margin:0;font-size:19px;line-height:1.4}.sheet-close{position:absolute;right:10px;top:9px;width:44px;height:44px;border:0;background:transparent;color:var(--secondary);font-size:28px}.sheet-body{padding:16px;overflow:auto}.detail-row{padding:11px 0;border-bottom:1px solid var(--line)}.detail-row:last-child{border-bottom:0}.detail-label{color:var(--muted);font-size:12px}.detail-value{margin-top:4px;line-height:1.6;overflow-wrap:anywhere}.sheet-action{width:100%;min-height:46px;margin-top:16px;border:0;border-radius:var(--radius);color:#fff;background:var(--brand);font-weight:800}.sheet-hint{margin-top:8px;color:var(--muted);font-size:12px;text-align:center}
    .error-state{padding:60px 20px;text-align:center}.error-state h2{font-size:20px}.error-state p{color:var(--secondary);line-height:1.65}
    [hidden]{display:none!important}
    @media (min-width:521px){.app{min-height:calc(100dvh - 24px);margin:12px auto}.nav{bottom:12px;border:1px solid var(--line);border-radius:8px}}
    @media (prefers-reduced-motion:reduce){.spinner{animation:none}}
  </style>
</head>
<body>
  <div id="app" class="app"><div class="loading"><div class="spinner"></div>正在读取小优工作台数据</div></div>
  <dialog id="detail-sheet" aria-label="证据详情">
    <div class="sheet-head"><h3 id="sheet-title">详情</h3><button class="sheet-close" id="sheet-close" aria-label="关闭">×</button></div>
    <div class="sheet-body"><div id="sheet-content"></div><button class="sheet-action" id="sheet-action">复制问题，回企业微信问小优</button><div class="sheet-hint">工作台只读，业务处理继续在企业微信完成</div></div>
  </dialog>
  <script>
  (()=>{
    "use strict";
    const token="__TOKEN__";
    const baseQuery="?token="+encodeURIComponent(token);
    const app=document.getElementById("app");
    const sheet=document.getElementById("detail-sheet");
    const details=new Map();
    const state={me:null,data:null,tab:"",program:"global",studentFilter:"attention",search:""};
    const roleMeta={
      teacher:{label:"老师",subtitle:"我的教学与服务工作",tabs:[["today","今日"],["students","学生"],["materials","我的积累"]]},
      manager:{label:"店长",subtitle:"门店运营与协作",tabs:[["today","今日现场"],["students","学生"],["team","团队"],["tasks","任务"]]},
      boss:{label:"老板",subtitle:"经营决策与小优进展",tabs:[["decisions","决策"],["business","经营"],["team","团队"],["xiaoyou","小优"]]}
    };
    const statusNames={pending:"待发送",queued:"已入队",sending:"发送中",sent:"已发送",replied:"已回复",verified:"已核验",failed:"失败",result_unknown:"结果未知",open:"进行中",active:"推进中",in_progress:"进行中",waiting_evidence:"等待证据",completed:"已完成",cancelled:"已取消",decision_pending:"待老板决定",evidence_ready:"证据已具备",validation_approved:"已批准验证",validating:"验证中",proposal_ready:"方案待确认"};
    function clean(value){return String(value??"").replace(/Hermes/gi,"小优").trim()}
    function h(value){return clean(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
    function list(value){return Array.isArray(value)?value:[]}
    function obj(value){return value&&typeof value==="object"&&!Array.isArray(value)?value:{}}
    function own(object,key){return Object.prototype.hasOwnProperty.call(object||{},key)}
    function value(object,key,suffix=""){return own(object,key)?h(object[key])+suffix:"待采集"}
    function status(value){const key=clean(value);return statusNames[key]||key||"状态待确认"}
    function formatTime(value){if(!value)return "更新时间待补";const d=new Date(value);if(Number.isNaN(d.getTime()))return h(value);return new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d)}
    function freshness(value){if(!value)return "数据时间待补";const d=new Date(value);if(Number.isNaN(d.getTime()))return "数据时间待补";const mins=Math.max(0,Math.round((Date.now()-d.getTime())/60000));if(mins<2)return "刚刚更新";if(mins<60)return mins+"分钟前更新";if(mins<1440)return Math.floor(mins/60)+"小时前更新";return formatTime(value)+"更新"}
    function levelTone(level){return clean(level)==="S"?"danger":clean(level)==="A"?"warning":"accent"}
    function registerDetail(title,rows,prompt){const id="detail-"+(details.size+1);details.set(id,{title,rows,prompt});return id}
    function detailItem({title,summary="",meta="",tone="",rows=[],prompt=""}){const id=registerDetail(title,rows,prompt||("请帮我展开说明“"+clean(title)+"”"));return `<button class="item ${tone}" data-detail="${id}"><span class="item-copy"><span class="item-title">${h(title)}</span>${summary?`<span class="item-summary">${h(summary)}</span>`:""}${meta?`<span class="item-meta">${h(meta)}</span>`:""}</span><span class="chevron" aria-hidden="true">›</span></button>`}
    function plainItem(title,summary="",meta="",tone=""){return `<div class="item ${tone}"><span class="item-copy"><span class="item-title">${h(title)}</span>${summary?`<span class="item-summary">${h(summary)}</span>`:""}${meta?`<span class="item-meta">${h(meta)}</span>`:""}</span></div>`}
    function row(label,value){return {label:clean(label),value:clean(value)||"待补"}}
    function empty(title,body){return `<div class="empty"><strong>${h(title)}</strong><p>${h(body)}</p></div>`}
    function section(title,body,note="",rawNote=false){return `<section class="section"><div class="section-head"><h3>${h(title)}</h3>${note?(rawNote?note:`<span class="section-note">${h(note)}</span>`):""}</div>${body}</section>`}
    function sourceLine(text,time=""){return `<div class="source-line"><span class="fact-label">事实来源</span> · ${h(text)}${time?` · ${h(freshness(time))}`:""}</div>`}
    function metric(label,val,foot){return `<div class="metric"><div class="metric-label">${h(label)}</div><div class="metric-value">${h(val)}</div><div class="metric-foot">${h(foot)}</div></div>`}
    function metricGrid(items){return `<div class="metrics">${items.map(item=>metric(...item)).join("")}</div>`}
    function taskFreshness(task){const labels={current:"当前",overdue:"已逾期",stale:"历史待核"};return labels[clean(task.freshness_state)]||"当前"}
    function taskRows(task){return [row("任务",task.title),row("学生",task.student_name||"未指定"),row("状态",status(task.status)),row("时间状态",taskFreshness(task)),row("级别",task.level||"C"),row("截止时间",task.due_at?formatTime(task.due_at):"未设置"),row("来源",task.source_label||task.assigned_by_name||"任务账本")];}
    function taskItem(task){const timing=taskFreshness(task);return detailItem({title:task.title||"未命名任务",summary:[task.student_name,status(task.status),timing==="当前"?"":timing].filter(Boolean).join(" · "),meta:(task.due_at?"截止 "+formatTime(task.due_at):"未设置截止时间")+" · "+(task.source_label||"任务账本"),tone:levelTone(task.level),rows:taskRows(task),prompt:"请帮我处理任务“"+clean(task.title||"未命名任务")+"”"})}
    function renderHeader(meta){const programLabels={global:"全机构",regular_tuoguan:"正式托管",summer_2026:"暑假项目"};const scope=state.me.role==="boss"?(programLabels[state.program]||"当前授权项目"):(list(state.me.program_scope).map(item=>programLabels[clean(item)]||clean(item)).join("、")||programLabels[state.me.default_program_id]||"当前授权项目");return `<header class="top"><div class="brand-row"><div class="brand-mark" aria-hidden="true">优</div><div class="brand-copy"><h1 class="brand-title">小优工作台</h1><div class="brand-sub">${h(meta.subtitle)}</div></div><span class="role-badge">${h(meta.label)}</span></div><div class="context"><span>${h(scope)}</span><span>${h(freshness(state.data.generated_at))}</span></div></header>`}
    function renderNav(meta){return `<nav class="nav" style="grid-template-columns:repeat(${meta.tabs.length},minmax(0,1fr))" aria-label="工作台导航">${meta.tabs.map(([key,label])=>`<button data-tab="${key}" class="${state.tab===key?"active":""}" aria-current="${state.tab===key?"page":"false"}">${h(label)}</button>`).join("")}</nav>`}
    function intro(eyebrow,title,summary){return `<div class="intro"><div class="eyebrow">${h(eyebrow)}</div><h2>${h(title)}</h2><p>${h(summary)}</p></div>`}
    function bind(){document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{state.tab=button.dataset.tab;render()});document.querySelectorAll("[data-detail]").forEach(button=>button.onclick=()=>openDetail(button.dataset.detail));const search=document.getElementById("student-search");if(search)search.oninput=e=>{state.search=e.target.value;const q=clean(state.search).toLowerCase();document.querySelectorAll("#student-results .item").forEach(item=>{item.hidden=Boolean(q&&!clean(item.textContent).toLowerCase().includes(q))})};document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{state.studentFilter=button.dataset.filter;renderMainOnly()});const selector=document.getElementById("program-select");if(selector)selector.onchange=async e=>{state.program=e.target.value;await loadData();render()}}
    function openDetail(id){const detail=details.get(id);if(!detail)return;document.getElementById("sheet-title").textContent=clean(detail.title);document.getElementById("sheet-content").innerHTML=detail.rows.map(item=>`<div class="detail-row"><div class="detail-label">${h(item.label)}</div><div class="detail-value">${h(item.value)}</div></div>`).join("");const action=document.getElementById("sheet-action");action.dataset.prompt=detail.prompt||("请帮我展开说明“"+clean(detail.title)+"”");sheet.showModal()}
    async function copyPrompt(){const prompt=document.getElementById("sheet-action").dataset.prompt||"请帮我展开说明";try{await navigator.clipboard.writeText(prompt);document.getElementById("sheet-action").textContent="已复制，回企业微信发送给小优";setTimeout(()=>document.getElementById("sheet-action").textContent="复制问题，回企业微信问小优",1800)}catch(_){window.prompt("复制后回企业微信发送给小优",prompt)}}
    document.getElementById("sheet-close").onclick=()=>sheet.close();document.getElementById("sheet-action").onclick=copyPrompt;sheet.addEventListener("click",event=>{if(event.target===sheet)sheet.close()});

    function teacherStudents(){const map=new Map();const add=(name,reason="",attention=false)=>{name=clean(name);if(!name)return;const current=map.get(name)||{name,reasons:[],attention:false};if(reason&&!current.reasons.includes(reason))current.reasons.push(reason);current.attention=current.attention||attention;map.set(name,current)};list(state.data.student_completion).forEach(item=>add(item.student_name));list(state.data.open_tasks).forEach(item=>add(item.student_name,"有开放任务",true));list(state.data.suggested_records).forEach(item=>add(item.student_name,item.reason||"近期记录待补",true));list(state.data.today_feedback).forEach(item=>add(item.student_name,"今天已有新记录"));return [...map.values()]}
    function teacherToday(data){const tasks=list(data.open_tasks);const todayTasks=list(data.today_tasks);const suggestions=list(data.suggested_records);const feedback=list(data.today_feedback);let priorities=todayTasks.slice(0,2).map(taskItem);suggestions.slice(0,Math.max(0,3-priorities.length)).forEach(item=>priorities.push(detailItem({title:item.student_name+"需要一条新观察",summary:item.reason||"近期服务证据待补",meta:"学生与记录账本",tone:"info",rows:[row("学生",item.student_name),row("原因",item.reason),row("下一步","回企业微信告诉小优今天观察到的真实情况")],prompt:"请帮我梳理"+clean(item.student_name)+"今天最值得记录的一件事"})));if(!priorities.length)priorities=[plainItem("今天没有明确待办","小优会继续根据任务和学生记录整理重点。","当前事实","accent")];const focusStudents=teacherStudents().filter(item=>item.attention).slice(0,3);return intro("今天",clean(data.display_name||state.me.display_name)+"，先把最重要的事看清楚","这里不排名、不计分，只展示你的任务、学生和已沉淀材料。")+section("小优今日提示",`<div class="list">${priorities.join("")}</div>`,"最多3项")+section("当前任务",tasks.length?`<div class="list">${tasks.slice(0,5).map(taskItem).join("")}</div>`:empty("当前没有开放任务","需要安排工作时，直接回企业微信告诉小优。"),"任务账本")+section("重点学生",focusStudents.length?`<div class="list">${focusStudents.map(item=>detailItem({title:item.name,summary:item.reasons.join("；"),meta:"本人负责学生",tone:"warning",rows:[row("学生",item.name),row("当前原因",item.reasons.join("；")),row("数据边界","仅展示本人授权范围")],prompt:"请帮我展开"+item.name+"当前需要关注的原因"})).join("")}</div>`:empty("当前没有达到提醒条件的学生","这表示当前数据中没有明确开放任务或记录缺口，不代表所有事实都已采集。"),"最多3名")+section("今日积累",feedback.length?`<div class="list">${feedback.slice(0,4).map(item=>detailItem({title:item.student_name||"学生记录",summary:item.summary||item.content||"已形成一条记录",meta:formatTime(item.created_at||item.recorded_at),rows:[row("学生",item.student_name),row("记录",item.summary||item.content),row("形成时间",formatTime(item.created_at||item.recorded_at)),row("用途",list(item.use_cases).join("、"))],prompt:"请帮我整理这条学生记录的可复用表达"})).join("")}</div>`:empty("今天还没有新的工作积累","你在企业微信说出真实观察后，小优会帮助整理。"),"只读")+sourceLine("任务、学生和记录账本",data.generated_at)}
    function teacherStudentsPage(data){const students=teacherStudents();const q=clean(state.search).toLowerCase();const filtered=students.filter(item=>(state.studentFilter!=="attention"||item.attention)&&(!q||item.name.toLowerCase().includes(q)));return intro("学生","先看需要关注的学生","这里只展示你当前负责的学生与真实任务、记录缺口。")+section("学生范围",`<div class="toolbar"><input id="student-search" class="search" value="${h(state.search)}" placeholder="搜索学生" aria-label="搜索学生"></div><div class="filters"><button class="filter ${state.studentFilter==="attention"?"active":""}" data-filter="attention">需要关注</button><button class="filter ${state.studentFilter==="all"?"active":""}" data-filter="all">全部学生</button></div>${filtered.length?`<div class="list" id="student-results">${filtered.map(item=>detailItem({title:item.name,summary:item.reasons.length?item.reasons.join("；"):"当前没有开放任务或明确记录缺口",meta:item.attention?"需要关注":"当前服务中",tone:item.attention?"warning":"",rows:[row("学生",item.name),row("当前状态",item.reasons.join("；")||"当前没有明确待办"),row("数据范围","本人负责且当前有效")],prompt:"请帮我查看"+item.name+"的当前服务情况"})).join("")}</div>`:empty("没有找到符合条件的学生","可切换“全部学生”或更换搜索词。")}`,students.length+"名")+sourceLine("学生责任关系、开放任务和近期记录",data.generated_at)}
    function teacherMaterials(data){const materials=obj(data.materials);const groups=[["最近有效记录",materials.quality_records],["家长沟通材料",materials.parent_communication],["成长报告材料",materials.growth_reports],["学生标签材料",materials.student_tags]];let html=intro("我的积累","把做过的工作沉淀下来","这些材料只服务你的工作，不进入公开排名或工资计算。");groups.forEach(([label,items])=>{items=list(items);html+=section(label,items.length?`<div class="list">${items.slice(0,8).map(item=>detailItem({title:item.student_name||label,summary:item.summary||item.content||"已形成可复用材料",meta:list(item.use_cases).join("、")||formatTime(item.created_at||item.recorded_at),rows:[row("学生",item.student_name),row("内容",item.summary||item.content),row("可用场景",list(item.use_cases).join("、")),row("时间",formatTime(item.created_at||item.recorded_at))],prompt:"请帮我展开并完善这条"+label})).join("")}</div>`:empty("暂时没有这类材料","继续在企业微信告诉小优真实工作过程，材料会从有效记录中形成。"),"只读")});return html+sourceLine("本人有效记录和已审核材料",data.generated_at)}

    function managerStudentRows(data){const risks=new Map(),teacherNames=new Map(list(obj(data.execution).teachers).map(item=>[clean(item.teacher_id),clean(item.teacher_name||item.teacher_id)]));list(obj(data.risk).priority_students).forEach(item=>{const name=clean(item.student_name||item.name);if(name)risks.set(name,clean(item.reason||item.risk||"存在需要关注的服务信号"))});list(obj(data.risk).long_unrecorded_students).forEach(name=>risks.set(clean(name),"近期有效记录不足"));const tasks=list(obj(obj(data.task_status).closure_evidence).missing_evidence_tasks);tasks.forEach(item=>{if(item.student_name)risks.set(clean(item.student_name),"任务等待证据")});return list(data.student_roster).map(item=>{const teacherId=clean(item.teacher_userid);return {name:clean(item.student_name),teacher:clean(item.teacher_name)||teacherNames.get(teacherId)||teacherId||"责任人待确认",campus:clean(item.campus_id),reason:risks.get(clean(item.student_name))||"",attention:risks.has(clean(item.student_name))}})}
    function managerToday(data){const taskStatus=obj(data.task_status),closure=obj(taskStatus.closure_evidence),safety=list(taskStatus.safety_risks),gaps=list(closure.missing_evidence_tasks),assistant=obj(data.hermes_assistant),confirmations=list(assistant.pending_confirmations);const taskCards=[...safety,...gaps].slice(0,5);const supported=list(assistant.top_suggestions).filter(item=>/任务|闭环|安全|证据/.test(clean(item.title)+clean(item.detail))).slice(0,3);return intro("今日现场","先看哪里可能断档","小优只把当前有证据的安全、任务和交接事项放到这里。")+section("安全与服务异常",safety.length?`<div class="list">${safety.map(taskItem).join("")}</div>`:empty("当前未发现需要立即处理的异常","结论基于当前已采集任务和记录，数据缺失会单独说明。"),"当前有效")+section("卡住或等待证据",taskCards.length?`<div class="list">${taskCards.map(taskItem).join("")}</div>`:empty("当前没有卡住的明确事项","已完成和已取消任务不会在这里复活。"),"任务账本")+section("小优现场建议",supported.length?`<div class="list">${supported.map(item=>detailItem({title:item.title,summary:item.detail,meta:"小优判断 · 基于任务事实",tone:"info",rows:[row("建议",item.title),row("依据",item.detail),row("边界","这是协作建议，不是绩效判断")],prompt:"请帮我展开这条现场建议并说明依据"})).join("")}</div>`:empty("当前没有新的现场建议","小优不会用旧覆盖率或历史事项填满页面。"),"有证据才展示")+section("待确认与交接",confirmations.length?`<div class="list">${confirmations.map(item=>detailItem({title:item.question||item.title||"待确认事项",summary:"需要回企业微信与小优继续确认",meta:status(item.status),tone:"warning",rows:[row("事项",item.question||item.title),row("状态",status(item.status)),row("来源",item.focus_key||"当前工作线程")],prompt:"请帮我处理这项待确认事项"})).join("")}</div>`:empty("当前没有待确认或交接事项","新的协作需要会在有事实对象时出现。"),"当前线程")+sourceLine("任务、闭环证据与当前工作线程",data.generated_at)}
    function managerStudentsPage(data){const students=managerStudentRows(data);const q=clean(state.search).toLowerCase(),filtered=students.filter(item=>(state.studentFilter!=="attention"||item.attention)&&(!q||item.name.toLowerCase().includes(q)||item.teacher.toLowerCase().includes(q)));return intro("学生","按服务状态找到需要协调的人","学生数量不是经营结论，重点看责任关系、开放任务和数据新鲜度。")+section("授权学生",`<div class="toolbar"><input id="student-search" class="search" value="${h(state.search)}" placeholder="搜索学生或责任老师" aria-label="搜索学生或责任老师"></div><div class="filters"><button class="filter ${state.studentFilter==="attention"?"active":""}" data-filter="attention">需要关注</button><button class="filter ${state.studentFilter==="all"?"active":""}" data-filter="all">全部学生</button></div>${filtered.length?`<div class="list" id="student-results">${filtered.map(item=>detailItem({title:item.name,summary:item.reason||"当前没有明确服务阻塞",meta:"责任人 "+item.teacher+(item.campus?" · "+item.campus:""),tone:item.attention?"warning":"",rows:[row("学生",item.name),row("责任人",item.teacher),row("当前关注",item.reason||"无明确待办"),row("项目/校区",item.campus||"当前授权范围")],prompt:"请帮我查看"+item.name+"当前服务是否需要协调"})).join("")}</div>`:empty("没有找到符合条件的学生","可切换全部学生或更换搜索词。")}`,students.length+"名")+sourceLine("授权学生、责任关系、任务和近期记录",data.generated_at)}
    function managerTeam(data){const teachers=list(obj(data.execution).teachers);return intro("团队","看谁需要支持，不做公开排名","这里只展示开放任务和明确证据缺口，帮助店长安排协作。")+section("老师支持",teachers.length?`<div class="list">${teachers.map(item=>{const reasons=[];if(Number(item.open_task_count||0))reasons.push(item.open_task_count+"个开放任务");if(list(item.stale_students).length)reasons.push(list(item.stale_students).length+"名学生记录待补");if(list(item.missing_growth_report_students).length)reasons.push(list(item.missing_growth_report_students).length+"份成长材料待补");return detailItem({title:item.teacher_name||item.teacher_id,summary:reasons.join("；")||"当前没有明确支持缺口",meta:"服务学生 "+value(item,"student_count")+"名",tone:reasons.length?"warning":"",rows:[row("老师",item.teacher_name||item.teacher_id),row("开放任务",item.open_task_count||0),row("记录待补学生",list(item.stale_students).join("、")||"无"),row("成长材料待补",list(item.missing_growth_report_students).join("、")||"无"),row("边界","协作支持，不是绩效排名")],prompt:"请帮我看看如何支持"+clean(item.teacher_name||item.teacher_id)}).replace("待采集名","待采集")}).join("")}</div>`:empty("当前没有可展示的团队服务关系","人员状态待完整投影时会诚实显示，不用零代替。"),"不排名")+sourceLine("人员责任关系、开放任务和记录证据",data.generated_at)}
    function managerTasks(data){const taskStatus=obj(data.task_status),closure=obj(taskStatus.closure_evidence),gaps=list(closure.missing_evidence_tasks),safety=list(taskStatus.safety_risks),events=list(closure.recent_events),counts=obj(taskStatus.open_by_status);return intro("任务","看清状态与关闭证据","任务写操作继续在企业微信完成，工作台不建立第二套状态。")+section("任务概况",metricGrid([["开放任务",value(obj(data.summary),"open_task_count"),"任务账本"],["等待证据",value(closure,"missing_evidence_count"),"闭环证据"],["安全事项",String(safety.length),"当前未关闭"],["最近完成",value(closure,"recent_completed_count"),"关闭事件"]])+sourceLine("任务与闭环账本",data.generated_at),"当前")+section("等待证据",gaps.length?`<div class="list">${gaps.map(item=>detailItem({title:item.task_title||"未命名任务",summary:"还缺："+list(item.missing_fields).join("、"),meta:[item.student_name,status(item.status)].filter(Boolean).join(" · "),tone:levelTone(item.level),rows:[row("任务",item.task_title),row("学生",item.student_name),row("缺少证据",list(item.missing_fields).join("、")),row("当前证据",item.evidence_summary),row("状态",status(item.status))],prompt:"请帮我推进任务“"+clean(item.task_title)+"”缺少的闭环证据"})).join("")}</div>`:empty("没有等待证据的任务","完整闭环和已取消任务不会再次提醒。"),"任务闭环")+section("安全事项",safety.length?`<div class="list">${safety.map(taskItem).join("")}</div>`:empty("当前没有开放安全事项","只代表现有任务账本没有未关闭安全任务。"),"高优先级")+section("最近完成",events.length?`<div class="list">${events.slice(0,8).map(item=>detailItem({title:item.task_title||"已关闭任务",summary:item.text||"已记录关闭事件",meta:formatTime(item.at)+" · "+status(item.action),rows:[row("任务",item.task_title),row("学生",item.student_name),row("关闭动作",status(item.action)),row("证据摘要",item.text),row("时间",formatTime(item.at))],prompt:"请帮我展开这项任务的关闭证据"})).join("")}</div>`:empty("暂时没有最近完成记录","完成结果以关闭事件账本为准。"),"只读")}

    function opportunityItem(item){const plan=obj(item.validation_plan);const planText=list(plan.steps||plan.actions).join("；")||clean(plan.summary||plan.method)||"验证方案待补";return detailItem({title:item.title||"新项目机会",summary:item.hypothesis||item.xiaoyou_judgement||"发现了值得验证的共同服务需求",meta:`${item.affected_student_count||0}名学生 · ${item.teacher_count||0}名老师 · ${item.evidence_period||"证据周期待补"}`,tone:item.requires_owner_decision?"warning":"info",rows:[row("机会状态",status(item.status)),row("内部证据",`${item.affected_student_count||0}名学生，${item.teacher_count||0}名老师，覆盖率${item.coverage_rate??"待补"}%`),row("证据周期",item.evidence_period),row("小优判断",item.xiaoyou_judgement||item.hypothesis),row("仍缺事实",list(item.missing_facts).join("；")||"暂无"),row("低成本验证",planText),row("边界",item.boundary||"待验证候选，不等于正式项目")],prompt:"请展开这个新项目机会，并说明是否值得进入验证"})}
    function bossDecisions(data){const employee=obj(data.hermes_employee),focus=obj(employee.focus_brief),safety=list(obj(data.task_status).safety_risks),opps=list(obj(data.project_opportunities).items).filter(item=>item.requires_owner_decision||item.status==="decision_pending"),opportunityTitles=opps.map(item=>clean(item.title)).filter(Boolean),questions=list(employee.open_questions).filter(item=>!opportunityTitles.some(title=>clean(item.question).includes(title))).slice(0,3);const decisions=[...opps.map(opportunityItem),...questions.map(item=>detailItem({title:item.question||"待老板确认",summary:"需要经营取舍或事实确认",meta:status(item.status),tone:"warning",rows:[row("待确认",item.question),row("状态",status(item.status)),row("工作焦点",item.focus_key)],prompt:"请帮我处理这项老板待确认事项"}))].slice(0,3);const report=obj(employee.daily_reports),receipts=[];["morning","evening"].forEach(kind=>{const item=obj(report[kind]);if(["sent","verified"].includes(clean(item.status)))receipts.push(plainItem((kind==="morning"?"早报":"晚报")+"已送达",formatTime(item.sent_at||item.queued_at),"执行回执","accent"))});return intro("决策","只看需要你判断的事","流水账和普通观察不会挤占首页；候选、已发送和已核验分开表达。")+section("需要我决定",decisions.length?`<div class="list">${decisions.join("")}</div>`:empty("当前没有需要你立即决定的事项","小优会继续推进已确认目标，出现真实取舍时再放到这里。"),"最多3项")+section("当前核心目标",focus.title&&focus.title!=="暂无活跃目标"?`<div class="list">${detailItem({title:focus.title,summary:focus.blocker||"暂无明确卡点",meta:(focus.phase||"当前阶段")+" · "+status(focus.status),tone:"info",rows:[row("目标",focus.title),row("阶段",focus.phase),row("阻塞",focus.blocker),row("下一步",focus.next_action),row("下次关注",focus.next_attention_at?formatTime(focus.next_attention_at):"按事实推进")],prompt:"请展开当前核心目标的阶段、阻塞和下一步"})}</div>`:empty("当前没有活跃经营目标","你可以在企业微信告诉小优新的经营目标。"),"目标账本")+section("高风险与趋势变化",safety.length?`<div class="list">${safety.slice(0,3).map(taskItem).join("")}</div>`:empty("当前未发现开放的高风险事项","只基于当前任务和记录，不用历史风险填充。"),"当前有效")+section("小优已推进",receipts.length?`<div class="list">${receipts.join("")}</div>`:empty("当前没有新的已核验执行回执","没有回执的候选不会写成“小优已完成”。"),"只认回执")+sourceLine("目标、attention、任务和执行回执",data.generated_at)}
    function bossBusiness(data){const summary=obj(data.summary),opps=obj(data.project_opportunities),reports=obj(obj(data.hermes_employee).daily_reports);const reportState=["morning","evening"].map(kind=>{const item=obj(reports[kind]);return (kind==="morning"?"早":"晚")+"报"+status(item.status||"未生成")}).join(" · ");const selector=`<select id="program-select" class="program-select" aria-label="切换项目"><option value="global" ${state.program==="global"?"selected":""}>全机构</option><option value="regular_tuoguan" ${state.program==="regular_tuoguan"?"selected":""}>正式托管</option><option value="summer_2026" ${state.program==="summer_2026"?"selected":""}>暑假项目</option></select>`;return intro("经营","把经营事实与小优判断分开看","数字来自业务账本；没有采集的数据不会伪装成零。")+section("经营概况",metricGrid([["当前学生",value(summary,"student_count"),"当前项目口径"],["今日有效记录",value(summary,"today_valid_records"),"记录账本"],["开放任务",value(summary,"open_task_count"),"任务账本"],["当前高风险",value(summary,"high_risk_count"),"未关闭事项"]])+sourceLine("学生、记录和任务账本",data.generated_at),selector,true)+section("日报交付",plainItem("固定汇报状态",reportState,"生成、入队、送达分别记录","accent")+sourceLine("日报运行与外发回执",data.generated_at),"真实回执")+section("新项目机会",list(opps.items).length?`<div class="list">${list(opps.items).slice(0,3).map(opportunityItem).join("")}</div>`+sourceLine("30天内部运营证据",opps.source_updated_at):empty("当前没有达到展示门槛的新项目机会","弱信号仍在内部观察，不会为了填满页面生成虚假机会。"),"最多3项")+`<div class="section"><div class="notice"><strong>机会边界</strong><span class="fact-label">内部证据</span> 与 <span class="judgement-label">小优判断</span> 会分开展示；老板未确认前，不联系员工、不创建验证任务、不视为立项。</div></div>`}
    function bossTeam(data){const teachers=list(obj(data.execution).teachers),managers=list(obj(data.execution).managers);return intro("团队","看服务阻塞，不看排名","团队页只帮助你判断谁需要支持，不展示工资、分数或聊天原文。")+section("老师服务状态",teachers.length?`<div class="list">${teachers.map(item=>{const reasons=[];if(Number(item.open_task_count||0))reasons.push(item.open_task_count+"个开放任务");if(list(item.stale_students).length)reasons.push(list(item.stale_students).length+"名学生记录待补");return detailItem({title:item.teacher_name||item.teacher_id,summary:reasons.join("；")||"当前没有明确服务阻塞",meta:"当前服务关系 · "+value(item,"student_count")+"名学生",tone:reasons.length?"warning":"",rows:[row("老师",item.teacher_name||item.teacher_id),row("服务学生",item.student_count),row("开放任务",item.open_task_count),row("需要支持",reasons.join("；")||"无明确事项"),row("边界","不展示排名、工资或私人对话")],prompt:"请帮我分析如何支持"+clean(item.teacher_name||item.teacher_id)}).replace("待采集名","待采集")}).join("")}</div>`:empty("当前没有完整团队投影","人员状态不足时不把缺失数据写成零。"),"不排名")+section("店长协作",managers.length?`<div class="list">${managers.map(item=>detailItem({title:item.name||item.user_id||"店长",summary:"查看当前授权范围内的协作状态",meta:item.position_label||"店长",rows:[row("人员",item.name||item.user_id),row("角色",item.position_label||"店长"),row("边界","仅展示真实开放事项")],prompt:"请帮我查看这位店长当前需要哪些经营支持"})).join("")}</div>`:empty("当前没有可展示的店长协作事项","没有真实开放事项时保持空状态。"),"当前事项")+sourceLine("人员责任关系、任务和记录证据",data.generated_at)}
    function bossXiaoyou(data){const employee=obj(data.hermes_employee),reports=obj(employee.daily_reports),touch=obj(employee.relationship_presence),work=list(employee.work_items);const reportItems=["morning","evening"].map(kind=>{const item=obj(reports[kind]);return detailItem({title:(kind==="morning"?"早报":"晚报")+" · "+status(item.status||"未生成"),summary:item.message||"当前没有生成记录",meta:formatTime(item.sent_at||item.queued_at),tone:["failed","result_unknown"].includes(clean(item.status))?"danger":"accent",rows:[row("汇报",kind==="morning"?"早报":"晚报"),row("状态",status(item.status||"未生成")),row("入队时间",formatTime(item.queued_at)),row("送达时间",formatTime(item.sent_at))],prompt:"请帮我检查固定汇报的真实送达状态"})});return intro("小优","看它是否真的在工作","这里展示推进状态和回执，不展示内部长日志，也不把候选写成成果。")+section("固定汇报",`<div class="list">${reportItems.join("")}</div>`,"运行回执")+section("正在推进",work.length?`<div class="list">${work.slice(0,5).map(item=>detailItem({title:item.title||"当前工作项",summary:item.next_action||item.focus_summary||"等待下一步事实",meta:(item.phase||"当前阶段")+" · "+status(item.status),tone:"info",rows:[row("工作项",item.title),row("状态",status(item.status)),row("当前阶段",item.phase),row("下一步",item.next_action),row("阻塞",item.blocker)],prompt:"请展开小优正在推进的这项工作"})).join("")}</div>`:empty("当前没有活跃工作项","小优会继续巡检机构事实；没有工作项不等于系统离线。"),"只显示当前事项")+section("主动联系",list(touch.items).length?`<div class="list">${list(touch.items).map(item=>detailItem({title:"联系"+(item.target_name||item.target_user_id||"相关人员")+" · "+status(item.status),summary:item.reason||item.value||"围绕明确工作事实",meta:item.suggested_send_at?formatTime(item.suggested_send_at):"时间待模型判断",tone:item.status==="failed"?"danger":"",rows:[row("对象",item.target_name||item.target_user_id),row("状态",status(item.status)),row("原因",item.reason),row("价值",item.value),row("发送时间",formatTime(item.suggested_send_at)),row("边界","不展示员工私聊原文")],prompt:"请帮我核对这次主动联系的发送和回复状态"})).join("")}</div>`:empty("当前没有新的主动联系记录","候选、入队、送达、回复和核验会分别显示。"),"不展示私聊正文")+sourceLine("日报、工作项、主动触达和外发回执",data.generated_at)}

    function page(){const role=state.me.role,data=state.data;if(role==="teacher")return state.tab==="students"?teacherStudentsPage(data):state.tab==="materials"?teacherMaterials(data):teacherToday(data);if(role==="manager")return state.tab==="students"?managerStudentsPage(data):state.tab==="team"?managerTeam(data):state.tab==="tasks"?managerTasks(data):managerToday(data);return state.tab==="business"?bossBusiness(data):state.tab==="team"?bossTeam(data):state.tab==="xiaoyou"?bossXiaoyou(data):bossDecisions(data)}
    function renderMainOnly(){details.clear();const main=document.getElementById("main");if(main){main.innerHTML=page();bind()}}
    function render(){details.clear();const meta=roleMeta[state.me.role]||roleMeta.teacher;if(!state.tab||!meta.tabs.some(([key])=>key===state.tab))state.tab=meta.tabs[0][0];app.innerHTML=renderHeader(meta)+`<main id="main">${page()}</main>`+renderNav(meta);bind()}
    async function fetchJson(url){const response=await fetch(url,{headers:{"Accept":"application/json"},cache:"no-store"});if(!response.ok){let message="工作台读取失败";try{const body=await response.json();message=body.error?.message||message}catch(_){}throw new Error(message)}return response.json()}
    async function loadData(){const api=state.me.role==="teacher"?"/tuoguan/api/teacher":"/tuoguan/api/boss";const program=state.me.role==="boss"&&state.program!=="global"?"&program_id="+encodeURIComponent(state.program):"";state.data=await fetchJson(api+baseQuery+program)}
    async function main(){try{state.me=await fetchJson("/tuoguan/api/me"+baseQuery);if(!roleMeta[state.me.role])throw new Error("当前身份暂未开放小优工作台");state.program=state.me.default_program_id==="global"?"global":state.me.default_program_id||"global";state.tab=roleMeta[state.me.role].tabs[0][0];await loadData();render()}catch(error){app.innerHTML=`<div class="error-state"><div class="brand-mark" style="margin:0 auto">优</div><h2>工作台暂时无法打开</h2><p>${h(error.message)}</p><p>请返回企业微信，重新向小优获取工作台链接。</p></div>`}}
    main();
  })();
  </script>
</body>
</html>"""
